#!/bin/bash

# Array of sci-fi corporation names (lowercase for consistency)
corps=(
  "weyland-yutani"
  "cyberdyne systems"
  "tyrell corporation"
  "omni consumer products"
  "shinra electric"
  "soylent corporation"
  "blue sun"
  "umbrella corporation"
  "zorg industries"
  "nakatomi trading"
  "massive dynamic"
  "ingen"
  "typhon corporation"
  "abstergo industries"
  "vault-tec"
  "black mesa"
  "aperture science"
  "stark industries"
  "oscorp"
  "lexcorp"
  "wayne enterprises"
  "tyrell mining"
  "nerv"
  "genetech"
  "virtucon"
  "megacorp"
  "e corp"
  "grayson enterprises"
  "kaiba corp"
  "lexxon"
  "tyrell pharma"
  "cerberus"
  "bluetek sciences"
  "delos inc"
  "better future"
  "rda"
  "neonet"
  "shaw industries"
  "kruger industrial"
  "protogen"
  "hyperion"
  "atlas corporation"
  "jakobs"
  "tediore"
  "maliwan"
  "novatech"
  "cosmodyne"
  "omega sector"
  "interstellar resources"
  "galactic freight"
  "transgalactic shipping"
  "cybercore"
  "nanodyne labs"
  "megabio research"
  "starforge weapons"
  "planetary mining"
  "lunar excavations"
  "astrotech"
  "gensys biotech"
  "vortex energy"
  "banking guild"
  "hyperspace transit"
  "starline aerospace"
  "biocore innovations"
  "soltech power"
  "cryogen industries"
  "fusion dynamics"
  "astromedic"
  "plasmaworks"
  "titanium defense"
  "quasar labs"
  "galacticom"
  "orbitronics"
  "proxima mining"
  "zenith robotics"
  "cosmos pharma"
  "helix dynamics"
  "nebula security"
  "interstel systems"
  "aurora aerospace"
)

# Get random corporation name
echo "${corps[$RANDOM % ${#corps[@]}]}"
